//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine_312
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dann
    {
        public int id { get; set; }
        public string familiya { get; set; }
        public string imya { get; set; }
        public string otechestvo { get; set; }
        public string gorod { get; set; }
        public Nullable<int> id_patients { get; set; }
    }
}
