//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine_312
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int id { get; set; }
        public string name_tovar { get; set; }
        public int kol { get; set; }
    }
}
